apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx
  annotations:
    configmap.reloader.stakater.com/reload: "my-sql"
  labels:
    app: mysql   
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1 
  template: 
    metadata:
      labels:
        app: mysql    
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
          - containerPort: 80        
          volumeMounts:
            - name: mysql-config
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-config
          configMap:
            name: my-sql
